Crud for moves Part 1
thesnowcoders-fh/sprky-chess pull request #16
Opened 2017-01-31 14:48 UTC by fleawig

I'm requesting this to be merged now so we can all continue with a functioning Move model that can save moves to database, and works with the PieceMover methods to update the board.
I started to work on Move CRUD, but creation will be dependent on Game params, so it makes sense to finish some Game CRUD first (so that moves can belong to games).
After this merge, I'll work on Game CRUD branch, then Move CRUD #2 branch.

2017-01-31 16:32 UTC, nrabbi approved these changes
Fixed the build errors that would have made it fail the codeship test. Overall, it looks good. Approved!

2017-01-31 18:33 UTC, fleawig commented
Updated to use integer input and the Position constructor. Everything works. Good teamwork, folks! Please review so we can merge.

2017-02-01 04:10 UTC, rongg requested changes

2017-02-01 04:10 UTC, rongg commented on app/controllers/games_controller.rb
>      moves << move2
Why are these from and to's in quotes? They should be integers

2017-02-01 05:04 UTC, rongg commented
I fixed the Games table so the status works with the enum in the Game model. You can create and save a game like this:

`game = Game.new(player_1_id: 1, player_2_id: 2, status: :created)`
 `game.save`

2017-02-01 10:38 UTC, fleawig commented
Since the requested change was so straightforward, and has been made, I'm going to merge the branch.

2017-02-01 10:38 UTC, fleawig commented
Also, thanks for changing the Game model, Ron!

2017-02-01 10:38 UTC, merged